# Generated by Django 6.0.2 on 2026-02-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('dp', models.ImageField(upload_to='photos')),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
