# Generated by Django 6.0.2 on 2026-03-06 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pimg', models.ImageField(upload_to='photos')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False, verbose_name='Available')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registermodel')),
            ],
        ),
    ]
