# Generated by Django 6.0.2 on 2026-03-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catname',
            new_name='catid',
        ),
    ]
