# Generated by Django 6.0.2 on 2026-03-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_catname_category_catid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catid',
            new_name='catname',
        ),
    ]
