# Generated by Django 6.0.2 on 2026-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_color_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='color',
            name='colorcode',
            field=models.CharField(max_length=10),
        ),
    ]
