# Generated by Django 6.0.2 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_product_color_alter_color_colorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='app1.color'),
        ),
    ]
