# Generated by Django 6.0.2 on 2026-03-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_registermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalprice', models.FloatField()),
                ('orderstatus', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registermodel')),
            ],
        ),
    ]
