# Generated by Django 5.1.5 on 2026-03-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finaltotal', models.FloatField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('paymode', models.CharField(max_length=10)),
                ('razorpay_orderid', models.CharField(blank=True, max_length=35, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registermodel')),
            ],
        ),
    ]
