# Generated by Django 5.1.5 on 2026-04-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registermodel')),
            ],
        ),
    ]
